mutation UpdateCity($data: CityInput!, $updateCityId: Int!) {
    updateCity(data: $data, id: $updateCityId) {
        id
        name
        latitude
        longitude
        users {
            id
            email
            }
        poi {
            id
            name
            address
        }
    }
}